# Generated by Django 4.0 on 2021-12-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('mana_cost', models.IntegerField()),
                ('type_line', models.CharField(max_length=1000)),
                ('expansion', models.CharField(max_length=1000)),
                ('ability_text', models.CharField(max_length=1000)),
                ('flavor_text', models.CharField(max_length=1000)),
            ],
        ),
    ]
