# Generated by Django 4.0 on 2022-01-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='expansion',
        ),
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
    ]
