# Generated by Django 4.0 on 2022-01-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_remove_card_expansion_remove_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='flavor_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
