# Generated by Django 4.0 on 2022-01-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_alter_card_flavor_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='type_line',
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(default='temp', max_length=1000, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='ability_text',
            field=models.CharField(max_length=1000, verbose_name='Ability'),
        ),
        migrations.AlterField(
            model_name='card',
            name='flavor_text',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Flavor Text'),
        ),
        migrations.AlterField(
            model_name='card',
            name='mana_cost',
            field=models.IntegerField(verbose_name='Mana cost'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Card name'),
        ),
    ]
